### ISSUE TITLE
For Antarctic Sea Ice Diagnostics, Use February instead of March

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#1]
"For the SH, the maximum occurs in September and the minimum in February, so it's almost symmetric compared to the Arctic."

**Comment by valentinaschueller** [comment]
This is already satisfied with the map tasks since the month is user-provided there. Think about changing this for the time series tasks!

**Comment by valentinaschueller** [comment]
Suggestion: Only pass the necessary files to `SeaIceTimeSeries`, instead of letting the task select. This lets the user decide whether they want to use March or February.

**Usage Example**

```yaml
- ece.mon.ice_time_series:
    hemisphere: south
    summer: "{{feb_file}}"
    winter: "{{sep_file}}"
    varname: sivolu
    domain: "{{rundir}}/domain_cfg.nc"
    dst: "{{mondir}}/sivol-south.nc"
- ece.mon.ice_time_series:
    hemisphere: north
    winter: "{{mar_file}}"
    summer: "{{sep_file}}"
    varname: sivolu
    domain: "{{rundir}}/domain_cfg.nc"
    dst: "{{mondir}}/sivol-south.nc"
```

Alternatively, these could be called `summer_file`, `winter_file`, `domain_file`.
