### ISSUE TITLE
Change Si3HemisSumMonthMeanTimeseries

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#108]
This task does more than it should, which makes its name unclear. Suggested new functionality:

```yaml
ece.mon.si3_hemis_sum_month_mean_timeseries:
    src: 
        - "{{mar_file}}"
        - "{{sep_file}}"
    varname: sivolu
    hemisphere: north
    dst: "{{mondir}}/si3_north_sum_mar+sep_mean_timeseries.nc"
```

The task:
* takes the data for `varname` from one or multiple SI3 month file(s)
* creates a weighted hemispheric sum
* changes metadata accordingly (but not the time bounds!)
* saves the cube to `dst`
