### ISSUE TITLE
Rework Presentation Task/Presentation Objects/Map Type Handling for Custom User Input

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#109]
```yaml
- ece.mon.presentation.markdown:
    src:
        - "{{mondir}}/expid_scalar.yml"
        - "{{mondir}}/tos_nemo_global_mean_year_mean_timeseries.nc"
        - file: "{{mondir}}/tos_nemo_year_mean_temporalmap.nc"
          colormap: "coolwarm"
          range: [0, 35]
```
--> Rework Presentation Task/Presentation Objects/Map Type Handling to support this new structure

_Originally posted by @valentinaschueller in https://github.com/valentinaschueller/scriptengine-tasks-ecearth/issues/65#issuecomment-680773093_
