### ISSUE TITLE
Different Colorbars for Different Diagnostics?

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#65]
E.g. white-blue for ice but red-white-blue for ocean/atmosphere temperature diagnostics. Make this user-configurable?

**Comment by valentinaschueller** [comment]
```yaml
- ece.mon.presentation.markdown:
    src:
        - "{{mondir}}/expid_scalar.yml"
        - "{{mondir}}/tos_nemo_global_mean_year_mean_timeseries.nc"
        - file: "{{mondir}}/tos_nemo_year_mean_temporalmap.nc"
          colormap: "coolwarm"
          range: [0, 35]
```
--> Rework Presentation Task/Presentation Objects/Map Type Handling to support this new structure
