### ISSUE TITLE
Decide on SimulatedLegs variant

### ISSUE THREAD

**Issue by valentinaschueller** [valentinaschueller/scriptengine-tasks-ecearth#91]
Currently, two versions of this task are implemented: version 1 counts the folders in src/output, version 2 gets information from context. Version 2 could be recreated just by the Scalar task. How necessary is this diagnostic and which version is more suitable?

**Comment by uwefladrich** [comment]
I think from the way the run time environment and the monitoring are used now, we could well get along with version 2, i.e. writing a context variable with `Scalar`. This was not so clear in the beginning, but I think now it would be simpler and therefore preferable.

**Comment by valentinaschueller** [comment]
The `SimulatedLegs` task will be removed in the next pull request. The diagnostic can be created in the future using the following YAML script:

```yaml
ece.mon.scalar:
    title: Simulated Legs
    value: "{{leg_num}}"
    dst: "{{mondir}}/sim-legs.yml"
```
